### PR TITLE
changed the couchr.request call to plain simple http.request call bec…

### PR DESCRIPTION
**Pull request by FranzPoize**
…ause couchr was hanging and never calling the callback

### CODE REVIEW

**Comment by janl** [comment]
whoa, do you have a test case that shows the issue?

**Comment by FranzPoize** [comment]
Yeah I could try to make something tomorrow.

**Comment by janl** [comment]
thank you! :)

**Comment by janl** [comment]
background: I’ve suspected something fishy here, but were never able to find anything, and it would not happen all the time.

Only comment I have already is: couchr nicely abstracted some parts of the HTTP handling/parsing away, maybe we can move some of the new code into a utils or library in this module, so we can keep only the higher-level db_updates logic in this file.

Otherwise, great find! :)

**Comment by FranzPoize** [comment]
Here is a repo with a hoodie app and a plugin that trigger the behavior https://github.com/FranzPoize/hoodie-task-test

The goal of the plugin is to write `Ok we gucci` to the console on a `type:change` task in a user database.

##### Setting up the app
npm link the test-plugin inside the tasktest hoodie app (it is named hoodie-plugin-test-task) so :
* `npm link` inside the test-plugin directory
* `npm link hoodie-plugin-test-task` inside the tasktest directory

##### Preparing for the test
* You should make sure the app is launched on port 6004 or change the port in `tasktest/setup-for-test-case.js` line 8
* Launch the app and run `node setup-for-test-case.js` in the tasktest directory
* The setup-for-test-case.js will create a user. You should then relaunch the hoodie app so that the plugin add the user db to the source
* Then create a document in the user with type test

**Comment by FranzPoize** [comment]
Hi I put the request code in a utils and kept the db_updates code as close as the old code.

If you have any opinion on the code structure go ahead I'm clearly not familiar with the hoodie codebase and I'm not really sure of how I put this PR together :)

**Comment by FranzPoize** [comment]
By the way would there be a way to differentiate between different event in the plugin API ?

Currently the only event provided is change which triggers on creation, change and deletion and you have to watch for the deleted properties in the plugin code.

If your okay with this I could provide a PR for this also.

**Comment by FranzPoize** [comment]
Don't merge right now there is still some issues with the refreshing of the updated queue.

**Comment by FranzPoize** [comment]
It seems that by basic hoodie app doesn't answer with a content-type of `application/json` but with `text/plain` on the `/_db_updates` route.
Is that a thing or is it just on my instance ?

**Comment by janl** [comment]
Sorry for taking so long to look into this!

> It seems that by basic hoodie app doesn't answer with a content-type of application/json but with text/plain on the /_db_updates route.
> Is that a thing or is it just on my instance ?

This is standard CouchDB behaviour. If you send an `Accept: application/json` header, you get a `Content-Type: application/json` back. Without that `Accept` header, CouchDB sends `text/plain` so it renders in browsers.

**Comment by janl** [comment]
> Don't merge right now there is still some issues with the refreshing of the updated queue

@FranzPoize: Which issues are these?

**Comment by janl** [comment]
So I tried to reproduce this:

> …
> Then create a document in the user with type test

At this point nothing happens, but if you write a document that looks like this, I get the “Ok we gucci” bit printed:

> {"type": "$test"}

E.g. Hoodie types must lead with a `$` sign.

screen shot 2015-06-20 at 14 46 09

screen shot 2015-06-20 at 14 46 18

**Comment by janl** [comment]
I still believe that there is something fishy here, but I’m not sure what that looks like.

**Comment by FranzPoize** [comment]
Hi @janl , I don't have time right now to look at that.

I'll definetly recheck my test case (maybe I didn't clearly understand how task worked) and keep you posted on my PR. If you could let it open for the moment I'd be glad.

**Comment by janl** [comment]
I’ll leave this open, no worries! :)

**Comment by boennemann** [comment]
hoodie-plugins-manager is now part of hoodie-server. During that cleanup we've replaced couchr with request.

**Comment by FranzPoize** [comment]
Thx for keeping us updated. We'll check the new version.

**Pull request closed without merging**
